services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmosdb-emulator
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
    volumes:
      - cosmosdb-data:/data/db
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://127.0.0.1:8081/_explorer/emulator.pem"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: always

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    volumes:
      - azurite-data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "10000"]
      interval: 5s
      timeout: 5s
      retries: 3

  function-app:
    build:
      context: ./src/DocumentVault.Function
      dockerfile: Dockerfile
    container_name: document-vault-function
    restart: always
    depends_on:
      cosmosdb: 
        condition: service_healthy
      azurite:
        condition: service_healthy
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - CosmosDb__Endpoint=https://cosmosdb:8081
      - CosmosDb__Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - CosmosDb__DatabaseName=DocumentVaultDB
      - CosmosDb__LinksContainerName=Links
      - CosmosDb__DocumentsContainerName=Documents
      - BlobStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - BlobStorage__ContainerName=documents
      - CdnEndpoint=http://web:80
      - AZURE_COSMOS_EMULATOR_CERTIFICATE_PATH=/tmp/cosmos-cert.pem
      - COSMOSDB_DISABLE_SSL_VALIDATION=true
      - AzureWebJobsSecretStorageType=files
      - AzureWebJobsSecretStoragePath=/root/.aspnet/DataProtection-Keys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/documents/test/link"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  web:
    build:
      context: ./src/DocumentVault.Web
      dockerfile: Dockerfile
    container_name: document-vault-web
    restart: always
    depends_on:
      cosmosdb:
        condition: service_healthy
      azurite:
        condition: service_healthy
      function-app:
        condition: service_started
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CosmosDb__Endpoint=https://cosmosdb:8081
      - CosmosDb__Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - CosmosDb__DatabaseName=DocumentVaultDB
      - CosmosDb__DocumentsContainerName=Documents
      - BlobStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - BlobStorage__ContainerName=documents
      - FunctionApp__HostName=http://function-app
      - FunctionApp__Key=
      - AZURE_COSMOS_EMULATOR_CERTIFICATE_PATH=/tmp/cosmos-cert.pem
      - COSMOSDB_DISABLE_SSL_VALIDATION=true

volumes:
  cosmosdb-data:
  azurite-data:
  data-protection: