name: DocumentVault Function App CD with env

on:
  push:
    branches: [ main ]
    paths:
      - 'src/DocumentVault.Function/**'
      - '.github/workflows/function-app-cd.yml'
  workflow_dispatch:
    inputs:
      function_app_name:
        description: 'Select the function app to deploy'
        required: false
        default: 'func-docvaultghpctl27yftf6'
        type: choice
        options:
          - func-docvaultghpctl27yftf6
          - func-docvault3ftuued3odxl4
          - func-docvaultefgaj2t73so3m

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '8.0'
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DEFAULT_APP: func-docvaultghpctl27yftf6
    steps:
      - uses: actions/checkout@v4

      - id: select
        shell: bash
        run: |
          SELECTED="${{ github.event.inputs.function_app_name }}"
          if [ -z "$SELECTED" ]; then
            SELECTED="${DEFAULT_APP}"
          fi
          echo "app_name=$SELECTED" >> "$GITHUB_OUTPUT"
          case "$SELECTED" in
            func-docvaultghpctl27yftf6) echo "client_id=AZURE_CLIENT_ID_FA_BRANCH" >> "$GITHUB_OUTPUT" ;;
            func-docvault3ftuued3odxl4) echo "client_id=AZURE_CLIENT_ID_ENV_SLOTS" >> "$GITHUB_OUTPUT" ;;
            func-docvaultefgaj2t73so3m) echo "client_id=AZURE_CLIENT_ID_DEPLOYMENT_CENTER" >> "$GITHUB_OUTPUT" ;;
            *) echo "client_id=AZURE_CLIENT_ID_FA_BRANCH" >> "$GITHUB_OUTPUT" ;;
          esac

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: |
          pushd './src/DocumentVault.Function'
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./output
          popd

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets[steps.select.outputs.client_id] }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - uses: Azure/functions-action@v1
        with:
          app-name: ${{ steps.select.outputs.app_name }}
          package: './src/DocumentVault.Function/output'
