name: DocumentVault Function App CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/DocumentVault.Function/**'
      - '.github/workflows/function-app-cd.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: 'func-docvault'
  DOTNET_VERSION: '9.0.x'
  AZURE_TENANT_ID: '70aae3b7-9f3b-484d-8f95-49e8fbb783c0'
  AZURE_SUBSCRIPTION_ID: 'd42a43c5-a3ff-4b1d-bb49-1d3a4f776848'
  AZURE_CLIENT_ID: ''                      # Output from functionAppFederatedIdentityClientId

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build function app
      run: |
        pushd './src/DocumentVault.Function'
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./output
        popd

    - name: 'Azure login using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './src/DocumentVault.Function/output'